import os
import re
from typing import List
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession

from database.session import get_db
from api.dependencies.auth import get_current_active_user
from models.user import User
from schemas.analytics import (
    AnalyticsDashboardResponse,
    AnalyticsReportResponse,
    ReportCreateRequest,
    ReportExportResponse,
    CareerReadinessBreakdown,
)
from services.analytics import AnalyticsService

router = APIRouter(prefix="/analytics", tags=["Analytics & Reports"])


@router.get("/dashboard", response_model=AnalyticsDashboardResponse, status_code=status.HTTP_200_OK)
async def get_analytics_dashboard(
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Retrieve aggregated analytics dashboard metrics, historical trend snapshots,
    recent reports list, and career readiness breakdown.
    """
    service = AnalyticsService(db)
    try:
        data = await service.get_dashboard_data(current_user.id)
        return data
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to load analytics dashboard: {str(e)}"
        )


@router.post("/reports", response_model=AnalyticsReportResponse, status_code=status.HTTP_201_CREATED)
async def generate_career_report(
    payload: ReportCreateRequest,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Trigger generation of a new premium analytics report containing
    latest career readiness score breakdowns, SWOT analyses, and recommended actions.
    """
    service = AnalyticsService(db)
    try:
        report = await service.generate_premium_report(
            user_id=current_user.id,
            report_type=payload.report_type,
            title=payload.title
        )
        return report
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate report: {str(e)}"
        )


@router.get("/reports", response_model=List[AnalyticsReportResponse], status_code=status.HTTP_200_OK)
async def list_career_reports(
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    List all premium analytics reports generated by the logged-in user.
    """
    service = AnalyticsService(db)
    try:
        reports = await service.report_repo.get_by_user_id_sorted(current_user.id)
        return reports
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to list reports: {str(e)}"
        )


@router.get("/reports/{id}", response_model=AnalyticsReportResponse, status_code=status.HTTP_200_OK)
async def get_report_details(
    id: UUID,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Fetch details and metrics breakdown data for a specific generated report.
    """
    service = AnalyticsService(db)
    report = await service.report_repo.get_by_id_and_user_id(id, current_user.id)
    if not report:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found or access denied."
        )
    return report


@router.post("/reports/{id}/export", response_model=ReportExportResponse, status_code=status.HTTP_200_OK)
async def export_career_report(
    id: UUID,
    export_type: str = "pdf",
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Export a generated report to PDF, Excel, CSV, or Markdown format.
    """
    service = AnalyticsService(db)
    try:
        export_result = await service.export_report(
            user_id=current_user.id,
            report_id=id,
            export_type=export_type
        )
        return export_result
    except ValueError as val_err:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(val_err)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to export report: {str(e)}"
        )


@router.get("/exports/download/{filename}", status_code=status.HTTP_200_OK)
async def download_exported_file(
    filename: str
):
    """
    Serve generated report files dynamically using Secure FileResponse checks
    to prevent path traversal.
    """
    # Sanitize input to allow only standard export file formats and prevent folder traversal
    if not re.match(r"^[a-zA-Z0-9_\-\.]+$", filename):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid export filename format."
        )

    export_path = os.path.abspath(os.path.join("apps/api/exports", filename))
    
    # Confirm location safety and existence
    if not os.path.exists(export_path) or not export_path.startswith(os.path.abspath("apps/api/exports")):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Exported file not found."
        )

    return FileResponse(
        path=export_path,
        filename=filename,
        media_type="application/octet-stream"
    )
