import os
import json
import csv
import logging
from datetime import datetime, date, timedelta
from typing import List, Dict, Any, Optional
from uuid import UUID, uuid4
import httpx
from sqlalchemy import select, and_, desc
from sqlalchemy.ext.asyncio import AsyncSession

# ReportLab imports for PDF Generation
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

# openpyxl imports for Excel Generation
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

from core.config import settings
from repositories.analytics import (
    AnalyticsReportRepository,
    AnalyticsSnapshotRepository,
    UserMetricRepository,
    ReportExportRepository,
)
from repositories.user import UserRepository
from repositories.resume import ResumeRepository, ATSReportRepository
from repositories.career import CareerRecommendationRepository
from repositories.roadmap import RoadmapRepository
from repositories.interview import InterviewSessionRepository
from models.analytics import AnalyticsReport, AnalyticsSnapshot, UserMetric, ReportExport

logger = logging.getLogger("careerpilot.analytics.service")


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas pattern to compute total page count dynamically
    and print 'Page X of Y' in the running footer.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        if self._pageNumber == 1:
            return  # Suppress on cover page
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))
        
        # Header
        self.drawString(54, 750, "CAREERPILOT AI — PROFESSIONAL PERFORMANCE METRICS")
        self.setFont("Helvetica", 8)
        self.drawRightString(558, 750, datetime.now().strftime("%Y-%m-%d"))
        
        # Header Rule
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.75)
        self.line(54, 742, 558, 742)
        
        # Footer Rule
        self.line(54, 55, 558, 55)
        
        # Footer
        self.setFont("Helvetica", 8)
        self.drawString(54, 40, "Confidential • Generated by CareerPilot AI")
        self.drawRightString(558, 40, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class AnalyticsService:
    """
    Enterprise-grade Analytics, Reporting, and Career Readiness Score Service.
    """

    def __init__(self, db: AsyncSession):
        self.db = db
        self.report_repo = AnalyticsReportRepository(db)
        self.snapshot_repo = AnalyticsSnapshotRepository(db)
        self.metric_repo = UserMetricRepository(db)
        self.export_repo = ReportExportRepository(db)

        # Repositories for gathering metric contexts
        self.user_repo = UserRepository(db)
        self.resume_repo = ResumeRepository(db)
        self.ats_repo = ATSReportRepository(db)
        self.career_repo = CareerRecommendationRepository(db)
        self.roadmap_repo = RoadmapRepository(db)
        self.interview_repo = InterviewSessionRepository(db)

    async def calculate_raw_metrics(self, user_id: UUID) -> Dict[str, Any]:
        """
        Gathers raw data points from all subsystems and evaluates individual scores (0-100).
        """
        # 1. Resume Score
        resume_score = 0.0
        resumes = await self.resume_repo.get_by_user_id(user_id)
        latest_resume_id = None
        if resumes:
            latest_resume = resumes[0]
            latest_resume_id = latest_resume.id
            if latest_resume.scores:
                resume_score = float(latest_resume.scores[0].overall_score)
            else:
                resume_score = 55.0  # Baseline for parsed text with no score entry

        # 2. ATS Score & Skill Gap Score
        ats_score = 0.0
        skill_gap_score = 0.0
        if latest_resume_id:
            ats_reports = await self.ats_repo.get_latest_by_resume_id(latest_resume_id)
            if ats_reports:
                ats_score = float(ats_reports.ats_score)
                # Deduct score based on missing keywords count
                gaps = ats_reports.missing_keywords or []
                skill_gap_score = max(0.0, 100.0 - (len(gaps) * 8.0))
            else:
                ats_score = 50.0
                skill_gap_score = 50.0
        else:
            ats_score = 0.0
            skill_gap_score = 0.0

        # 3. Career Match Score
        career_match_score = 0.0
        recs = await self.career_repo.get_by_user_id(user_id)
        if recs and recs[0].matches:
            # Take average of top 3 career matches
            top_matches = recs[0].matches[:3]
            career_match_score = sum(m.match_score for m in top_matches) / len(top_matches)
        else:
            career_match_score = 0.0

        # 4. Roadmap Completion
        roadmap_completion = 0.0
        roadmaps = await self.roadmap_repo.get_by_user_id(user_id)
        if roadmaps:
            latest_roadmap = roadmaps[0]
            milestones = latest_roadmap.milestones
            if milestones:
                roadmap_completion = sum(m.completion_percentage for m in milestones) / len(milestones)
            else:
                roadmap_completion = 0.0

        # 5. Interview Readiness
        interview_readiness = 0.0
        interviews = await self.interview_repo.get_by_user_id(user_id)
        completed_interviews = [i for i in interviews if i.status == "completed"]
        if completed_interviews:
            latest_interview = completed_interviews[0]
            interview_readiness = float(latest_interview.readiness_score or latest_interview.score or 0)
        else:
            interview_readiness = 0.0

        # 6. Learning Streak & Consistency
        learning_streak = 0
        # Calculate active streak based on consecutive days of activity in last 14 days
        active_dates = set()
        # Add roadmap completion timestamps
        if roadmaps:
            for record in roadmaps[0].progress_records:
                active_dates.add(record.created_at.date())
        # Add interview attempts
        for i in interviews:
            active_dates.add(i.started_at.date())
        
        # Calculate consecutive streak ending today
        today = date.today()
        current_date = today
        while current_date in active_dates:
            learning_streak += 1
            current_date -= timedelta(days=1)
            
        # Fallback to activity counts if no consecutive dates exist
        if learning_streak == 0:
            learning_streak = min(7, len(active_dates))

        return {
            "resume_score": resume_score,
            "ats_score": ats_score,
            "career_match_score": career_match_score,
            "skill_gap_score": skill_gap_score,
            "roadmap_completion": roadmap_completion,
            "interview_readiness": interview_readiness,
            "learning_streak": learning_streak,
        }

    async def get_or_create_latest_metrics(self, user_id: UUID) -> UserMetric:
        """
        Computes, caches, and returns user metrics row.
        """
        raw = await self.calculate_raw_metrics(user_id)
        
        # Career Readiness Score Formula:
        # Resume Quality (15%) + Average ATS & Skill Gap (20%) + Career Match (15%) + Roadmap Progress (20%) + Interview (20%) + Learning Streak (10%)
        learning_streak_score = min(10.0, float(raw["learning_streak"])) * 10.0
        avg_skill_coverage = (raw["ats_score"] + raw["skill_gap_score"]) / 2.0
        
        readiness_score = (
            (raw["resume_score"] * 0.15) +
            (avg_skill_coverage * 0.20) +
            (raw["career_match_score"] * 0.15) +
            (raw["roadmap_completion"] * 0.20) +
            (raw["interview_readiness"] * 0.20) +
            (learning_streak_score * 0.10)
        )
        
        # Overall Growth Score calculation relative to baseline
        overall_growth = max(0.0, readiness_score - 20.0)

        existing = await self.metric_repo.get_by_user_id(user_id)
        metric_data = {
            "user_id": user_id,
            "resume_score": raw["resume_score"],
            "ats_score": raw["ats_score"],
            "career_match_score": raw["career_match_score"],
            "skill_gap_score": raw["skill_gap_score"],
            "roadmap_completion": raw["roadmap_completion"],
            "interview_readiness": raw["interview_readiness"],
            "learning_streak": raw["learning_streak"],
            "career_readiness_score": round(readiness_score, 1),
            "overall_growth_score": round(overall_growth, 1),
        }

        if existing:
            return await self.metric_repo.update(db_obj=existing, obj_in=metric_data)
        else:
            return await self.metric_repo.create(obj_in=metric_data)

    async def get_career_readiness_breakdown(self, user_id: UUID) -> Dict[str, Any]:
        """
        Generates full analysis breakdown of each metric.
        """
        metrics = await self.get_or_create_latest_metrics(user_id)
        
        return {
            "career_readiness_score": metrics.career_readiness_score,
            "resume_quality": {
                "score": metrics.resume_score,
                "weight": 0.15,
                "status": "Excellent" if metrics.resume_score >= 80 else "Needs Improvement" if metrics.resume_score < 60 else "Good",
                "description": "Assesses structure, spelling, impact statements, and formatting quality."
            },
            "skill_coverage": {
                "score": (metrics.ats_score + metrics.skill_gap_score) / 2.0,
                "weight": 0.20,
                "status": "Excellent" if metrics.ats_score >= 80 else "Critical Gaps" if metrics.ats_score < 55 else "Aligned",
                "description": "Measures coverage of key requirements and core technical concepts."
            },
            "career_alignment": {
                "score": metrics.career_match_score,
                "weight": 0.15,
                "status": "Optimal" if metrics.career_match_score >= 75 else "Vague" if metrics.career_match_score < 50 else "Adequate",
                "description": "Calculates alignment of goals and past work with target roles."
            },
            "roadmap_progress": {
                "score": metrics.roadmap_completion,
                "weight": 0.20,
                "status": "On Track" if metrics.roadmap_completion >= 40 else "Stalled" if metrics.roadmap_completion < 10 else "Steady",
                "description": "Tracks active progress across milestones and skill challenges."
            },
            "interview_performance": {
                "score": metrics.interview_readiness,
                "weight": 0.20,
                "status": "Ready" if metrics.interview_readiness >= 75 else "Unprepared" if metrics.interview_readiness < 40 else "Improving",
                "description": "Evaluates communication, depth, and structural thinking from mock sessions."
            },
            "learning_consistency": {
                "score": min(10.0, float(metrics.learning_streak)) * 10.0,
                "weight": 0.10,
                "status": "Consistent" if metrics.learning_streak >= 5 else "Inactive" if metrics.learning_streak < 2 else "Average",
                "description": "Calculates streak metrics based on daily database touchpoints."
            },
            "overall_growth_score": metrics.overall_growth_score
        }

    async def generate_ai_insights(self, user_id: UUID, breakdown: Dict[str, Any]) -> Dict[str, Any]:
        """
        Uses Gemini 2.5 Flash to generate SWOT analysis and recommended roadmap iterations.
        """
        prompt = f"""Generate a high-quality, professional SWOT analysis and career report.
Candidate Career Readiness Metrics:
- Overall Readiness: {breakdown['career_readiness_score']}/100
- Resume Quality: {breakdown['resume_quality']['score']}/100 ({breakdown['resume_quality']['status']})
- Skill Coverage: {breakdown['skill_coverage']['score']}/100 ({breakdown['skill_coverage']['status']})
- Target Career Alignment: {breakdown['career_alignment']['score']}/100 ({breakdown['career_alignment']['status']})
- Roadmap Milestones Complete: {breakdown['roadmap_progress']['score']}% ({breakdown['roadmap_progress']['status']})
- Interview Simulation Readiness: {breakdown['interview_performance']['score']}/100 ({breakdown['interview_performance']['status']})
- Learning Streak: {breakdown['learning_consistency']['score']/10} consecutive days

Analyze these indicators and return a clean JSON payload mapping EXACTLY to this schema:
{{
  "strengths": ["list of 3 key structural strengths"],
  "weaknesses": ["list of 3 identified weak areas"],
  "opportunities": ["list of 2 market/growth opportunities"],
  "risks": ["list of 2 career/interview risk areas"],
  "career_suggestions": "Paragraph of career advice.",
  "roadmap_suggestions": "Paragraph of roadmap milestones optimization.",
  "interview_suggestions": "Paragraph of interview improvement actions.",
  "next_steps": ["list of 3 immediate actionable next steps"]
}}
Output ONLY the raw JSON format. No markdown blocks, backticks, or prefixing comments."""

        system_instruction = "You are a Chief Talent Analyst and Executive Recruiter. Output strict, valid JSON matching the schema."
        
        try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{settings.GEMINI_DEFAULT_MODEL}:generateContent?key={settings.GEMINI_API_KEY}"
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    url,
                    headers={"Content-Type": "application/json"},
                    json={
                        "contents": [
                            {
                                "role": "user",
                                "parts": [{"text": f"{system_instruction}\n\n{prompt}"}]
                            }
                        ]
                    }
                )
                if response.status_code == 200:
                    res_data = response.json()
                    raw_reply = res_data["candidates"][0]["content"]["parts"][0]["text"].strip()
                    # Strip markdown blocks if returned
                    if "```json" in raw_reply:
                        raw_reply = raw_reply.split("```json")[1].split("```")[0].strip()
                    elif "```" in raw_reply:
                        raw_reply = raw_reply.split("```")[1].split("```")[0].strip()
                    return json.loads(raw_reply)
                else:
                    logger.error(f"Gemini API returned error: {response.text}")
        except Exception as e:
            logger.error(f"Failed to generate SWOT via Gemini: {e}")

        # Bulletproof fallback SWOT generator if AI model is unreachable
        return {
            "strengths": [
                f"Candidate exhibits a strong target alignment score of {breakdown['career_alignment']['score']}/100.",
                "Structure and layout of technical components are consistent.",
                f"Active learning consistency maintained with a {int(breakdown['learning_consistency']['score']/10)}-day activity index."
            ],
            "weaknesses": [
                "ATS optimization gaps exist in resume keywords mapping.",
                "Roadmap progress requires structured checkpoint completions.",
                "Mock interview readiness needs closer focus on architectural depth."
            ],
            "opportunities": [
                "Target industry demands candidates with verified skill gap coverage.",
                "Completing milestones unlocks higher mock interview match capabilities."
            ],
            "risks": [
                "Low interview score risks early-stage technical screening failures.",
                "Inconsistent learning blocks timeline progression targets."
            ],
            "career_suggestions": "Leverage your target career alignment to focus on high-impact backend engineering positions.",
            "roadmap_suggestions": "Prioritize database and architecture milestones to close core technical gaps.",
            "interview_suggestions": "Focus on explaining structural choices during mock coding interviews.",
            "next_steps": [
                "Complete the pending system design roadmap milestone.",
                "Optimize resume file with missing keywords identified in ATS.",
                "Take a 30-minute mock coding simulation session."
            ]
        }

    async def get_snapshots_history(self, user_id: UUID, days: int = 30) -> List[AnalyticsSnapshot]:
        """
        Fetch snapshots history for trend rendering.
        """
        end_date = date.today()
        start_date = end_date - timedelta(days=days)
        return await self.snapshot_repo.get_by_user_id_and_date_range(user_id, start_date, end_date)

    async def create_snapshot(self, user_id: UUID) -> AnalyticsSnapshot:
        """
        Creates or updates a snapshot entry for today.
        """
        metrics = await self.get_or_create_latest_metrics(user_id)
        today = date.today()
        
        # Check if snapshot exists for today
        query = select(AnalyticsSnapshot).where(
            and_(AnalyticsSnapshot.user_id == user_id, AnalyticsSnapshot.snapshot_date == today)
        )
        result = await self.db.execute(query)
        existing = result.scalar_one_or_none()

        snapshot_data = {
            "user_id": user_id,
            "snapshot_date": today,
            "resume_score": metrics.resume_score,
            "ats_score": metrics.ats_score,
            "career_match_score": metrics.career_match_score,
            "skill_gap_score": metrics.skill_gap_score,
            "roadmap_completion": metrics.roadmap_completion,
            "interview_readiness": metrics.interview_readiness,
            "learning_streak": metrics.learning_streak,
            "career_readiness_score": metrics.career_readiness_score,
            "overall_growth_score": metrics.overall_growth_score,
        }

        if existing:
            return await self.snapshot_repo.update(db_obj=existing, obj_in=snapshot_data)
        else:
            return await self.snapshot_repo.create(obj_in=snapshot_data)

    async def generate_premium_report(self, user_id: UUID, report_type: str, title: Optional[str] = None) -> AnalyticsReport:
        """
        Compiles all telemetry data, fetches SWOT insights, and writes report data block.
        """
        breakdown = await self.get_career_readiness_breakdown(user_id)
        insights = await self.generate_ai_insights(user_id, breakdown)
        
        report_title = title or f"Career Performance Report — {report_type.capitalize()}"
        report_data = {
            "breakdown": breakdown,
            "insights": insights,
            "generated_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        report_obj = await self.report_repo.create(obj_in={
            "user_id": user_id,
            "report_type": report_type.lower(),
            "title": report_title,
            "summary": f"Comprehensive career analytics report highlighting a {breakdown['career_readiness_score']}/100 overall readiness score.",
            "data": report_data
        })

        # Save snapshot automatically as part of report creation
        await self.create_snapshot(user_id)
        return report_obj

    async def get_dashboard_data(self, user_id: UUID) -> Dict[str, Any]:
        """
        Collects latest metrics, trend history, and recent premium reports for dashboard views.
        """
        metrics = await self.get_or_create_latest_metrics(user_id)
        snapshots = await self.get_snapshots_history(user_id, days=30)
        recent_reports = await self.report_repo.get_by_user_id_sorted(user_id, limit=5)
        breakdown = await self.get_career_readiness_breakdown(user_id)
        insights = await self.generate_ai_insights(user_id, breakdown)

        return {
            "latest_metrics": metrics,
            "snapshots": snapshots,
            "recent_reports": recent_reports,
            "readiness_breakdown": breakdown,
            "growth_insights": insights
        }

    async def export_report(self, user_id: UUID, report_id: UUID, export_type: str) -> Dict[str, Any]:
        """
        Export generated report to PDF, CSV, Excel, or Markdown.
        """
        report = await self.report_repo.get_by_id_and_user_id(report_id, user_id)
        if not report:
            raise ValueError("Report not found or access denied.")

        export_dir = os.path.abspath("apps/api/exports")
        os.makedirs(export_dir, exist_ok=True)
        
        filename = f"careerpilot_report_{report.id}.{export_type.lower()}"
        file_path = os.path.join(export_dir, filename)
        export_url = f"/api/v1/analytics/exports/download/{filename}"

        if export_type.lower() == "pdf":
            self._generate_pdf_file(file_path, report)
        elif export_type.lower() == "excel":
            self._generate_excel_file(file_path, report)
        elif export_type.lower() == "csv":
            self._generate_csv_file(file_path, report)
        elif export_type.lower() == "markdown":
            self._generate_markdown_file(file_path, report)
        else:
            raise ValueError(f"Unsupported export format: {export_type}")

        export_obj = await self.export_repo.create(obj_in={
            "user_id": user_id,
            "report_id": report.id,
            "export_type": export_type.lower(),
            "export_url": export_url
        })

        return {
            "id": export_obj.id,
            "report_id": report.id,
            "export_type": export_type.lower(),
            "export_url": export_url,
            "created_at": export_obj.created_at
        }

    def _generate_pdf_file(self, file_path: str, report: AnalyticsReport):
        """
        ReportLab layout builder generating an executive Deloitte/McKinsey-style PDF report.
        """
        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Color definitions
        c_primary = colors.HexColor("#0f172a") # Slate 900
        c_secondary = colors.HexColor("#2563eb") # Blue 600
        c_body = colors.HexColor("#334155") # Slate 700
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            "CoverTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=32,
            leading=38,
            textColor=c_primary,
            spaceAfter=15
        )
        subtitle_style = ParagraphStyle(
            "CoverSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=16,
            leading=22,
            textColor=c_secondary,
            spaceAfter=40
        )
        h1_style = ParagraphStyle(
            "Heading1",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=c_primary,
            spaceBefore=18,
            spaceAfter=8,
            keepWithNext=True
        )
        h2_style = ParagraphStyle(
            "Heading2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=c_secondary,
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=c_body,
            spaceAfter=10
        )
        bullet_style = ParagraphStyle(
            "Bullet",
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )

        story = []

        # ----------------------------------------------------
        # COVER PAGE
        # ----------------------------------------------------
        story.append(Spacer(1, 150))
        story.append(Paragraph("CAREERPILOT AI", subtitle_style))
        story.append(Paragraph(report.title, title_style))
        story.append(Paragraph(f"Report Type: {report.report_type.upper()}", subtitle_style))
        story.append(Spacer(1, 100))
        
        metadata_table = Table(
            [
                [Paragraph("<b>Author:</b>", body_style), Paragraph("CareerPilot Analytics Engine", body_style)],
                [Paragraph("<b>Date Generated:</b>", body_style), Paragraph(report.data["generated_date"], body_style)],
                [Paragraph("<b>Classification:</b>", body_style), Paragraph("Strictly Confidential", body_style)]
            ],
            colWidths=[120, 300]
        )
        metadata_table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(metadata_table)
        story.append(PageBreak())

        # ----------------------------------------------------
        # TABLE OF CONTENTS / EXECUTIVE SUMMARY
        # ----------------------------------------------------
        story.append(Paragraph("Executive Summary", h1_style))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            f"This executive performance report evaluates the candidate's career readiness score at "
            f"<b>{report.data['breakdown']['career_readiness_score']}/100</b>. The evaluation covers structural resume audits, "
            f"ATS keyword optimization profiles, skill coverage roadmaps, mock interview performance, and streak activity patterns. "
            f"Key metrics demonstrate areas of high target alignment balanced by critical action recommendations outlined below.",
            body_style
        ))
        story.append(Spacer(1, 15))

        # ----------------------------------------------------
        # DETAILED METRICS TABLE
        # ----------------------------------------------------
        story.append(Paragraph("Key Readiness Breakdown", h1_style))
        story.append(Spacer(1, 5))
        
        breakdown = report.data["breakdown"]
        table_data = [
            [Paragraph("<b>Evaluation Category</b>", body_style), 
             Paragraph("<b>Weight</b>", body_style), 
             Paragraph("<b>Score</b>", body_style), 
             Paragraph("<b>Status Check</b>", body_style)]
        ]

        categories = [
            ("Resume Quality", breakdown["resume_quality"]),
            ("Skill Coverage", breakdown["skill_coverage"]),
            ("Goal Alignment", breakdown["career_alignment"]),
            ("Roadmap Progress", breakdown["roadmap_progress"]),
            ("Interview Readiness", breakdown["interview_performance"]),
            ("Consistency Metrics", breakdown["learning_consistency"])
        ]

        for name, details in categories:
            table_data.append([
                Paragraph(name, body_style),
                Paragraph(f"{int(details['weight'] * 100)}%", body_style),
                Paragraph(f"{details['score']}/100", body_style),
                Paragraph(details["status"], body_style)
            ])

        metrics_table = Table(table_data, colWidths=[160, 80, 100, 160])
        metrics_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ]))
        story.append(metrics_table)
        story.append(Spacer(1, 25))

        # ----------------------------------------------------
        # AI INSIGHTS & SWOT ANALYSIS
        # ----------------------------------------------------
        story.append(Paragraph("AI Insight Engine Analysis (SWOT)", h1_style))
        story.append(Spacer(1, 8))
        
        insights = report.data["insights"]
        
        swot_matrix_data = [
            [
                Paragraph("<b>Strengths</b><br/>" + "<br/>".join([f"• {s}" for s in insights["strengths"]]), body_style),
                Paragraph("<b>Weaknesses</b><br/>" + "<br/>".join([f"• {w}" for w in insights["weaknesses"]]), body_style)
            ],
            [
                Paragraph("<b>Opportunities</b><br/>" + "<br/>".join([f"• {o}" for o in insights["opportunities"]]), body_style),
                Paragraph("<b>Risks</b><br/>" + "<br/>".join([f"• {r}" for r in insights["risks"]]), body_style)
            ]
        ]
        
        swot_table = Table(swot_matrix_data, colWidths=[250, 250])
        swot_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#ecfdf5")), # Green tint for Strengths
            ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#fff7ed")), # Orange tint for Weaknesses
            ("BACKGROUND", (0, 1), (0, 1), colors.HexColor("#eff6ff")), # Blue tint for Opportunities
            ("BACKGROUND", (1, 1), (1, 1), colors.HexColor("#fef2f2")), # Red tint for Risks
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ]))
        story.append(swot_table)
        story.append(PageBreak())

        # ----------------------------------------------------
        # STRATEGIC NEXT ACTION PLANS
        # ----------------------------------------------------
        story.append(Paragraph("Recommended Action Plan", h1_style))
        story.append(Spacer(1, 10))
        
        story.append(Paragraph("<b>Resume Optimization Suggestions:</b>", h2_style))
        story.append(Paragraph(insights["career_suggestions"], body_style))
        story.append(Spacer(1, 5))

        story.append(Paragraph("<b>Roadmap Milestone Targets:</b>", h2_style))
        story.append(Paragraph(insights["roadmap_suggestions"], body_style))
        story.append(Spacer(1, 5))

        story.append(Paragraph("<b>Interview Readiness Tweaks:</b>", h2_style))
        story.append(Paragraph(insights["interview_suggestions"], body_style))
        story.append(Spacer(1, 15))

        story.append(Paragraph("<b>Priority Next Action Steps:</b>", h2_style))
        for idx, step in enumerate(insights["next_steps"]):
            story.append(Paragraph(f"<b>{idx+1}.</b> {step}", bullet_style))

        # Build Document using NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)

    def _generate_excel_file(self, file_path: str, report: AnalyticsReport):
        """
        Creates styled Excel sheets containing breakdown scores, snapshots, and SWOT insights.
        """
        wb = openpyxl.Workbook()
        
        # ----------------------------------------------------
        # SHEET 1: READINESS BREAKDOWN
        # ----------------------------------------------------
        ws1 = wb.active
        ws1.title = "Readiness Breakdown"
        ws1.views.sheetView[0].showGridLines = True
        
        # Define Styling elements
        navy_header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
        title_font = Font(name="Calibri", size=16, bold=True, color="1E3A8A")
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        bold_font = Font(name="Calibri", size=11, bold=True)
        regular_font = Font(name="Calibri", size=11)
        align_left = Alignment(horizontal="left", vertical="center")
        align_right = Alignment(horizontal="right", vertical="center")
        align_center = Alignment(horizontal="center", vertical="center")
        
        thin_border = Border(
            left=Side(style='thin', color='CBD5E1'),
            right=Side(style='thin', color='CBD5E1'),
            top=Side(style='thin', color='CBD5E1'),
            bottom=Side(style='thin', color='CBD5E1')
        )
        double_bottom_border = Border(
            top=Side(style='thin', color='000000'),
            bottom=Side(style='double', color='000000')
        )

        ws1.cell(row=1, column=1, value=report.title).font = title_font
        ws1.cell(row=2, column=1, value=f"Generated: {report.data['generated_date']}").font = Font(name="Calibri", size=10, italic=True)
        
        headers = ["Category", "Weight", "Score", "Status Check", "Description"]
        for col_idx, header in enumerate(headers, 1):
            cell = ws1.cell(row=4, column=col_idx, value=header)
            cell.font = header_font
            cell.fill = navy_header_fill
            cell.alignment = align_center if col_idx != 5 else align_left
            cell.border = thin_border
            
        breakdown = report.data["breakdown"]
        categories = [
            ("Resume Quality", breakdown["resume_quality"]),
            ("Skill Coverage", breakdown["skill_coverage"]),
            ("Goal Alignment", breakdown["career_alignment"]),
            ("Roadmap Progress", breakdown["roadmap_progress"]),
            ("Interview Readiness", breakdown["interview_performance"]),
            ("Consistency Metrics", breakdown["learning_consistency"])
        ]
        
        current_row = 5
        for name, details in categories:
            ws1.cell(row=current_row, column=1, value=name).font = bold_font
            ws1.cell(row=current_row, column=2, value=details["weight"]).font = regular_font
            ws1.cell(row=current_row, column=3, value=details["score"]).font = regular_font
            ws1.cell(row=current_row, column=4, value=details["status"]).font = regular_font
            ws1.cell(row=current_row, column=5, value=details["description"]).font = regular_font
            
            # Format percentages and numbers
            ws1.cell(row=current_row, column=2).number_format = '0%'
            ws1.cell(row=current_row, column=3).number_format = '0'
            
            for c in range(1, 6):
                cell = ws1.cell(row=current_row, column=c)
                cell.border = thin_border
                cell.alignment = align_left if c in [1, 4, 5] else align_center
            current_row += 1
            
        # Summary total row
        ws1.cell(row=current_row, column=1, value="Career Readiness Score").font = bold_font
        total_cell = ws1.cell(row=current_row, column=3, value=breakdown["career_readiness_score"])
        total_cell.font = bold_font
        total_cell.alignment = align_center
        
        for col in range(1, 6):
            ws1.cell(row=current_row, column=col).border = double_bottom_border

        # ----------------------------------------------------
        # SHEET 2: SWOT INSIGHTS
        # ----------------------------------------------------
        ws2 = wb.create_sheet(title="SWOT Insights")
        ws2.views.sheetView[0].showGridLines = True
        ws2.cell(row=1, column=1, value="SWOT Analysis & Recommendations").font = title_font
        
        insights = report.data["insights"]
        
        # Write strengths
        ws2.cell(row=3, column=1, value="Strengths").font = bold_font
        for idx, s in enumerate(insights["strengths"], 4):
            ws2.cell(row=idx, column=1, value=f"• {s}").font = regular_font
            
        # Write weaknesses
        ws2.cell(row=3, column=3, value="Weaknesses").font = bold_font
        for idx, w in enumerate(insights["weaknesses"], 4):
            ws2.cell(row=idx, column=3, value=f"• {w}").font = regular_font

        # Write opportunities
        ws2.cell(row=8, column=1, value="Opportunities").font = bold_font
        for idx, o in enumerate(insights["opportunities"], 9):
            ws2.cell(row=idx, column=1, value=f"• {o}").font = regular_font

        # Write risks
        ws2.cell(row=8, column=3, value="Risks").font = bold_font
        for idx, r in enumerate(insights["risks"], 9):
            ws2.cell(row=idx, column=3, value=f"• {r}").font = regular_font

        # Auto-adjust column widths across sheets
        for sheet in [ws1, ws2]:
            for col in sheet.columns:
                max_len = 0
                for cell in col:
                    val = str(cell.value or '')
                    if '\n' in val:
                        val = max(val.split('\n'), key=len)
                    max_len = max(max_len, len(val))
                col_letter = get_column_letter(col[0].column)
                sheet.column_dimensions[col_letter].width = max(max_len + 3, 12)
                
        wb.save(file_path)

    def _generate_csv_file(self, file_path: str, report: AnalyticsReport):
        """
        Exports a flat CSV row structure.
        """
        breakdown = report.data["breakdown"]
        with open(file_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["Metadata Type", "Category", "Score / Weight Value", "Status Status", "Details"])
            writer.writerow(["Overview", "Title", report.title, "", ""])
            writer.writerow(["Overview", "Readiness Score", breakdown["career_readiness_score"], "", "Overall Unified Score"])
            writer.writerow(["Overview", "Growth Score", breakdown["overall_growth_score"], "", "Growth Score"])
            
            categories = [
                ("Resume Score", breakdown["resume_quality"]),
                ("Skill Score", breakdown["skill_coverage"]),
                ("Career Score", breakdown["career_alignment"]),
                ("Roadmap Score", breakdown["roadmap_progress"]),
                ("Interview Score", breakdown["interview_performance"]),
                ("Consistency Score", breakdown["learning_consistency"])
            ]
            for label, obj in categories:
                writer.writerow(["Metric Breakdown", label, obj["score"], obj["status"], obj["description"]])

    def _generate_markdown_file(self, file_path: str, report: AnalyticsReport):
        """
        Exports a clean, reader-friendly markdown report structure.
        """
        breakdown = report.data["breakdown"]
        insights = report.data["insights"]
        
        lines = [
            f"# {report.title}",
            f"**Generated Date:** {report.data['generated_date']}",
            f"**Overall Readiness Score:** {breakdown['career_readiness_score']}/100",
            f"**Growth Index:** {breakdown['overall_growth_score']}/100",
            "",
            "## Executive Summary",
            "This career readiness report outlines recommendations mapped against candidate performance indexes.",
            "",
            "## Score Card Breakdown",
            "| Evaluation Area | Weight | Score | Status | Description |",
            "| :--- | :--- | :--- | :--- | :--- |",
            f"| Resume Quality | 15% | {breakdown['resume_quality']['score']}/100 | {breakdown['resume_quality']['status']} | {breakdown['resume_quality']['description']} |",
            f"| Skill Coverage | 20% | {breakdown['skill_coverage']['score']}/100 | {breakdown['skill_coverage']['status']} | {breakdown['skill_coverage']['description']} |",
            f"| Career Alignment | 15% | {breakdown['career_alignment']['score']}/100 | {breakdown['career_alignment']['status']} | {breakdown['career_alignment']['description']} |",
            f"| Roadmap Milestones | 20% | {breakdown['roadmap_progress']['score']}% | {breakdown['roadmap_progress']['status']} | {breakdown['roadmap_progress']['description']} |",
            f"| Mock Interviews | 20% | {breakdown['interview_performance']['score']}/100 | {breakdown['interview_performance']['status']} | {breakdown['interview_performance']['description']} |",
            f"| Daily Activity | 10% | {breakdown['learning_consistency']['score']/10} days | {breakdown['learning_consistency']['status']} | {breakdown['learning_consistency']['description']} |",
            "",
            "## SWOT insights",
            "### Strengths",
            "\n".join([f"- {s}" for s in insights["strengths"]]),
            "",
            "### Weaknesses",
            "\n".join([f"- {w}" for w in insights["weaknesses"]]),
            "",
            "### Opportunities",
            "\n".join([f"- {o}" for o in insights["opportunities"]]),
            "",
            "### Risks",
            "\n".join([f"- {r}" for r in insights["risks"]]),
            "",
            "## Action Plan Recommendations",
            f"### Career Optimization:\n{insights['career_suggestions']}",
            f"### Skill Roadmap Steps:\n{insights['roadmap_suggestions']}",
            f"### Interview Simulations:\n{insights['interview_suggestions']}",
            "",
            "### Immediate Next Actions",
        ]
        for idx, step in enumerate(insights["next_steps"]):
            lines.append(f"{idx+1}. {step}")
            
        with open(file_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
