"""create_analytics_tables

Revision ID: 4c057f240cb5
Revises: 43cb654ddb3a
Create Date: 2026-06-15 16:48:51.595550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c057f240cb5'
down_revision: Union[str, None] = '43cb654ddb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_analytics_reports_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_reports'))
    )
    op.create_index(op.f('idx_analytics_reports_report_type'), 'analytics_reports', ['report_type'], unique=False)
    op.create_index(op.f('idx_analytics_reports_user_id'), 'analytics_reports', ['user_id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('resume_score', sa.Float(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('career_match_score', sa.Float(), nullable=False),
    sa.Column('skill_gap_score', sa.Float(), nullable=False),
    sa.Column('roadmap_completion', sa.Float(), nullable=False),
    sa.Column('interview_readiness', sa.Float(), nullable=False),
    sa.Column('learning_streak', sa.Integer(), nullable=False),
    sa.Column('career_readiness_score', sa.Float(), nullable=False),
    sa.Column('overall_growth_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_analytics_snapshots_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_snapshots'))
    )
    op.create_index(op.f('idx_analytics_snapshots_snapshot_date'), 'analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('idx_analytics_snapshots_user_id'), 'analytics_snapshots', ['user_id'], unique=False)
    op.create_table('user_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_score', sa.Float(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('career_match_score', sa.Float(), nullable=False),
    sa.Column('skill_gap_score', sa.Float(), nullable=False),
    sa.Column('roadmap_completion', sa.Float(), nullable=False),
    sa.Column('interview_readiness', sa.Float(), nullable=False),
    sa.Column('learning_streak', sa.Integer(), nullable=False),
    sa.Column('career_readiness_score', sa.Float(), nullable=False),
    sa.Column('overall_growth_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_metrics_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_metrics'))
    )
    op.create_index(op.f('idx_user_metrics_user_id'), 'user_metrics', ['user_id'], unique=True)
    op.create_table('report_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('export_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analytics_reports.id'], name=op.f('fk_report_exports_report_id_analytics_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_report_exports_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_exports'))
    )
    op.create_index(op.f('idx_report_exports_report_id'), 'report_exports', ['report_id'], unique=False)
    op.create_index(op.f('idx_report_exports_user_id'), 'report_exports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_report_exports_user_id'), table_name='report_exports')
    op.drop_index(op.f('idx_report_exports_report_id'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('idx_user_metrics_user_id'), table_name='user_metrics')
    op.drop_table('user_metrics')
    op.drop_index(op.f('idx_analytics_snapshots_user_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('idx_analytics_snapshots_snapshot_date'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('idx_analytics_reports_user_id'), table_name='analytics_reports')
    op.drop_index(op.f('idx_analytics_reports_report_type'), table_name='analytics_reports')
    op.drop_table('analytics_reports')
    # ### end Alembic commands ###
