"""create_career_recommendations

Revision ID: b590157d2469
Revises: 31df51377950
Create Date: 2026-06-15 11:59:40.544855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b590157d2469'
down_revision: Union[str, None] = '31df51377950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_version', sa.String(length=50), nullable=False),
    sa.Column('recommendation_result', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_career_recommendations_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_recommendations'))
    )
    op.create_index(op.f('idx_career_recommendations_user_id'), 'career_recommendations', ['user_id'], unique=False)
    op.create_table('career_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('career_name', sa.String(length=100), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['career_recommendations.id'], name=op.f('fk_career_matches_recommendation_id_career_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_matches'))
    )
    op.create_index(op.f('idx_career_matches_career_name'), 'career_matches', ['career_name'], unique=False)
    op.create_index(op.f('idx_career_matches_recommendation_id'), 'career_matches', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_career_matches_recommendation_id'), table_name='career_matches')
    op.drop_index(op.f('idx_career_matches_career_name'), table_name='career_matches')
    op.drop_table('career_matches')
    op.drop_index(op.f('idx_career_recommendations_user_id'), table_name='career_recommendations')
    op.drop_table('career_recommendations')
    # ### end Alembic commands ###
