"""Add roadmap models

Revision ID: bb7042afa5d8
Revises: b590157d2469
Create Date: 2026-06-15 12:21:40.157387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7042afa5d8'
down_revision: Union[str, None] = 'b590157d2469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_career', sa.String(length=255), nullable=False),
    sa.Column('timeline', sa.String(length=100), nullable=False),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('roadmap_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_roadmaps_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmaps'))
    )
    op.create_index(op.f('idx_roadmaps_target_career'), 'roadmaps', ['target_career'], unique=False)
    op.create_index(op.f('idx_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_milestones_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_milestones'))
    )
    op.create_index(op.f('idx_roadmap_milestones_roadmap_id'), 'roadmap_milestones', ['roadmap_id'], unique=False)
    op.create_table('roadmap_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['roadmap_milestones.id'], name=op.f('fk_roadmap_progress_milestone_id_roadmap_milestones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_progress_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_progress'))
    )
    op.create_index(op.f('idx_roadmap_progress_milestone_id'), 'roadmap_progress', ['milestone_id'], unique=False)
    op.create_index(op.f('idx_roadmap_progress_roadmap_id'), 'roadmap_progress', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_roadmap_progress_roadmap_id'), table_name='roadmap_progress')
    op.drop_index(op.f('idx_roadmap_progress_milestone_id'), table_name='roadmap_progress')
    op.drop_table('roadmap_progress')
    op.drop_index(op.f('idx_roadmap_milestones_roadmap_id'), table_name='roadmap_milestones')
    op.drop_table('roadmap_milestones')
    op.drop_index(op.f('idx_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('idx_roadmaps_target_career'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
